caas:
  build: .
  links:
   - redis:redis
   - mysql:mysql
  environment:
    - HOSTNAME="REDIS_HOSTNAME"
  ports:
   - "80:80"

redis:
  image: redis:latest
  ports:
    - "6379:6379"

mysql:
  image: mysql:5.6
  ports:
    - "3306:3306"
  environment:
    - MYSQL_ROOT_PASSWORD=my-secret-pw
