caas:
  build: .
  links:
   - redis:redis
   - mysql:mysql
  environment:
    - CDN_URL="acd84eeb1b7b98b2dec5-9f5608ae56f41b0c88d873b8b4c5cc36.r22.cf2.rackcdn.com"
    - CDN_ASSET_URL="c3dcd810e2e5862353ca-bc79add51f9bad46177fcbc8055b750c.r72.cf2.rackcdn.com"
    - DB_USERNAME="root"
    - DB_DATABASE="caas"
    - DB_PASSWORD="my-secret-pw"
    - APP_DEBUG="true"
  ports:
   - "80:80"

redis:
  image: redis:latest
  ports:
    - "6379:6379"

mysql:
  image: mysql:5.6
  ports:
    - "3306:3306"
  environment:
    - MYSQL_ROOT_PASSWORD=my-secret-pw
